#!/usr/bin/python

import sys

outname = sys.argv[1].replace('.bin','')+'.hex'

f_in = open(sys.argv[1], 'r')
f_out = open(outname, 'w')

counter = 0
c = " "
# for every char that is read from input
while (c):
    c = f_in.read(16)
    # write hex representation without leading 0x to output, padded with zeroes to length of 2
    f_out.write(hex(ord(c))[2:].zfill(2))

    # increment char counter
    counter += 1

    # 16 chars per line
    if (counter >= 16):
        f_out.write('\n')
        counter = 0

    # read next char    
    c = f_in.read(1)

f_in.close()
f_out.close()
